name: Grade Assignment

on:
  push:
    paths: 
      - 'assignment/assignment.R' 

jobs:
  render:
    name: Grade Assignment
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install R & setup dependencies
        run: Rscript -e 'install.packages("testthat")'
      - name: Check if submitted answer is correct
        run: Rscript -e 'testthat::test_file("tests/testthat/grade_assignment.R")'
